### ISSUE TITLE
Remove usage of jQuery

### ISSUE THREAD

**Issue by josemarluedke** [offirgolan/ember-burger-menu#105]
HI there! Thanks for this project. It is awesome.

I would like to use this in one app that we don't want to ship jQuery and with the movement in the Ember itself to [allow jQuery to be optional](https://github.com/emberjs/rfcs/pull/294), it seems to be a great moment to think about that. 

I would like to understand that ware the required changes needed to allow us to not use jQuery within this project.

I would be interesting to layout the required changes so someone could pick this up and do the work. 

Thanks again for your work in this amazing project.

- [x] Remove usage of jquery in addon component [#109]
- [x] Remove usage of jquery event in `triggerSwipeEvent` test helper [#111]
- [x] Remove usage of jquery in tests [#111]

**Comment by acorncom** [comment]
I'd be interested in seeing this happen as well. Can probably pitch in to help if we can come up with a quest issue to knock everything out ...

**Comment by josemarluedke** [comment]
Just got a PR for removing the jquery usage in the components. 

There are other instances of jquery, but they are only in test env. It would be awesome if someone else took the other items.

**Comment by josemarluedke** [comment]
@offirgolan If you do find time, I would love if you took a look at migrating `triggerSwipeEvent` out of jQuery. 

I can take a look myself on removing the remaining jQuery usage in the tests.
